package com.hisobchi.bot.user.entity;

public enum UserState {
    IDLE,
    WAITING_EXPENSE_AMOUNT,
    WAITING_EXPENSE_CATEGORY,
    WAITING_EXPENSE_DESCRIPTION,
    WAITING_INCOME_AMOUNT,
    WAITING_INCOME_DESCRIPTION,
    WAITING_VOICE_CONFIRMATION,
    WAITING_AMOUNT_EDIT,
    WAITING_CATEGORY_EDIT,
    WAITING_DESCRIPTION_EDIT,
    WAITING_NEW_CATEGORY_NAME,
    WAITING_NEW_CATEGORY_EMOJI,
    WAITING_CUSTOM_DATE,
    WAITING_DAILY_PROFIT_CASH,
    WAITING_DAILY_PROFIT_CARD,
    WAITING_DEBT_AMOUNT,
    WAITING_DEBT_PERSON,
    WAITING_DEBT_DATE,
    WAITING_DEBT_PAYMENT_METHOD,
    WAITING_DEBT_EXTEND_DATE,
    WAITING_DEBT_EDIT_AMOUNT,
    WAITING_DEBT_EDIT_PERSON,
    WAITING_DEBT_EDIT_DATE
}
